// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwhQUkL590P4_5Ev9E_hpYZWD4-N3e28',
    appId: '1:471588739201:android:48e76a07edc72be0391580',
    messagingSenderId: '471588739201',
    projectId: 'beginner-yoga-a7abe',
    storageBucket: 'beginner-yoga-a7abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJUe2Fo-bYaFUjS2E0TqfVdDd0SvGvBVE',
    appId: '1:471588739201:ios:5f6071483740b109391580',
    messagingSenderId: '471588739201',
    projectId: 'beginner-yoga-a7abe',
    storageBucket: 'beginner-yoga-a7abe.appspot.com',
    iosBundleId: 'com.example.yogaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKk53-VjriqyY94DgYy2NgZXL9sWgDzFM',
    appId: '1:471588739201:web:35dd895834729b45391580',
    messagingSenderId: '471588739201',
    projectId: 'beginner-yoga-a7abe',
    authDomain: 'beginner-yoga-a7abe.firebaseapp.com',
    storageBucket: 'beginner-yoga-a7abe.appspot.com',
    measurementId: 'G-HETX679TDR',
  );
}
